### ISSUE TITLE
Issue when service routing with original message(string payload)

### ISSUE THREAD

**Issue by chaminda** [ballerina-lang/ballerina#1334]
I have below two services. once I invoke the [1], it will call to [2] with the same message(in-comming string payload) which I sent.
I am getting "could not get any response" error in postman(rest client).
[1]http://localhost:9090/paymentapi/dopayment (with text payload)
[2]http://localhost:9090/modules/checkModule

Once I print the response it will print with some binary data. Only if I build the string payload and sent(other than the one I originally sent), it works as expected.
[3]
 *)*M���L��

Below are the codes for services above.

@BasePath ("/modules")
service modules {
    @POST
    @Path("/checkModule")
    resource checkModule (message mod){
    message respns;
    string module;
    boolean istrue;
    string[] modules;
    int i;
    modules = ["sampath","ezcash", "hnb", "starpoint"];
    module = message:getStringPayload(mod);
    istrue = false;
    i = 0;
        while(i < array:length(modules)){
            if(string:equalsIgnoreCase(module,modules[i])){
                istrue = true;
                break;
              }
            i=i+1;
        }
    respns = new message();
    message:setStringPayload(respns, string:valueOf(istrue));
    reply respns;
    }

}

@BasePath ("/paymentapi")
service paymentgw {
    @POST
    @Path("/dopayment")
    resource dopayment (message m){
        http:HTTPConnector modEP = new http:HTTPConnector("http://localhost:9090/modules");
        message response;
        string modrespns;
        string mode;
        response = new message();
        response = http:HTTPConnector.post(modEP, "/checkModule", m);
        modrespns = message:getStringPayload(response);
        system:println("Response " + modrespns);
        if(string:equalsIgnoreCase(modrespns, "true")){
            //implement here
            system:println("PASSED");
        }
        reply response;
    }

}

**Comment by pubudu91** [comment]
As of v0.95.4, the above scenario of reading the response from the backend and then forwarding it again back to the client is not supported. Whether to allow this behaviour or not is an ongoing discussion atm. Given below is the code snippets given above, modified with the latest syntax.
```ballerina
import ballerina.net.http;

@http:configuration {basePath:"/modules"}
service<http> modulesService {

    @http:resourceConfig {
        methods:["POST"],
        path:"/checkModule"
    }
    resource checkModule (http:Request request, http:Response response) {
        string module = request.getStringPayload();
        boolean isTrue = false;
        string[] modules = ["sampath", "ezcash", "hnb", "starpoint"];

        int i = 0;
        while (i < lengthof modules) {
            if (module.equalsIgnoreCase(modules[i])) {
                isTrue = true;
                break;
            }

            i = i + 1;
        }

        response.setStringPayload("" + isTrue);
        _ = response.send();
    }
}

@http:configuration {basePath:"/paymentapi"}
service<http> paymentgw {

    @http:resourceConfig {
        methods:["POST"],
        path:"/dopayment"
    }
    resource doPayment (http:Request request, http:Response response) {
        endpoint<http:HttpClient> modEP {
            create http:HttpClient("http://localhost:9090/modules", {});
        }

        http:Response clientResponse;
        clientResponse, _ = modEP.forward("/checkModule", request);

        string resPayload = clientResponse.getStringPayload();
        println("Response " + resPayload);

        if (resPayload.equalsIgnoreCase("true")) {
            println("PASSED");
        }

        _ = response.forward(clientResponse);
    }
}
```

**Comment by pubudu91** [comment]
Tested this in v0.970.0-alpha1-SNAPSHOT and it's working. Therefore, closing this issue.
```ballerina
import ballerina/http;
import ballerina/io;

endpoint http:ServiceEndpoint paymentEP {
    port: 9090
};

endpoint http:SimpleClientEndpoint modEP {
    url: "http://localhost:8080/modules"
};

@http:ServiceConfig {basePath:"/paymentapi"}
service<http:Service> paymentgw bind paymentEP {

    @http:ResourceConfig {
        methods:["POST"],
        path:"/dopayment"
    }
    doPayment (endpoint outboundEP, http:Request request) {
        var clientResponse = modEP -> forward("/checkModule", request);

        match clientResponse {
            http:Response resp => {
                string resPayload = "";

                match resp.getStringPayload() {
                    string payload => resPayload = payload;
                    http:PayloadError => int x = 0;
                }

                io:println("Response " + resPayload);

                if (resPayload.equalsIgnoreCase("true")) {
                    io:println("PASSED");
                }

                _ = outboundEP -> forward(resp);
            }

            http:HttpConnectorError err => {io:println(err);}
        }
    }
}

endpoint http:ServiceEndpoint modulesEP {
    port: 8080
};

@http:ServiceConfig {basePath:"/modules"}
service<http:Service> modulesService bind modulesEP {

    @http:ResourceConfig {
        methods:["POST"],
        path:"/checkModule"
    }
    checkModule (endpoint outboundEP, http:Request request) {
        string module = "";
        match request.getStringPayload() {
            string payload => module = payload;
            http:PayloadError => int x = 0;
        }

        boolean isTrue = false;
        string[] modules = ["sampath", "ezcash", "hnb", "starpoint"];

        int i = 0;
        while (i < lengthof modules) {
            if (module.equalsIgnoreCase(modules[i])) {
                isTrue = true;
                break;
            }

            i = i + 1;
        }

        http:Response response = {};
        response.setStringPayload("" + isTrue);
        _ = outboundEP -> respond(response);
    }
}
```
