### ISSUE TITLE
[Enhancement] Include transactional control to faciliate Competing Consumer pattern

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/ballerina#1638]
In order to support patterns similar to Competing Consumer[1] a mechanism which is similar to load-balancing endpoint in ESB is needed.

[1] https://docs.wso2.com/display/IntegrationPatterns/Competing+Consumers

**Comment by uthaiyashankar** [comment]
Can define load balance endpoint as follows:
endpoint http:ClientEndpoint lbEP {
    targets: [
             {uri:"http://localhost:9090/mock1"},
             {uri:"http://localhost:9090/mock2"},
             {uri:"http://localhost:9090/mock3"}
             ]
};

For more details, please have a look at https://github.com/ballerina-lang/ballerina/blob/master/docs/ballerina-by-example/examples/http-load-balancer/http-load-balancer.bal
