### ISSUE TITLE
Links in HTTP2 Server connector doc give 404

### ISSUE THREAD

**Issue by mefarazath** [ballerina-lang/ballerina#2386]
http://ballerinalang.org/docs/user-guide/0.8/server-connectors/http2-server/

![image](https://cloud.githubusercontent.com/assets/5237653/26191453/8bd88602-3bcb-11e7-9cab-a8fc88e84275.png)

**Comment by uthaiyashankar** [comment]
This document (user-guide) is no longer in ballerinalang. Hence, resolving the issue.
