### ISSUE TITLE
No way to restrict annotations to in-annotation variables

### ISSUE THREAD

**Issue by manuranga** [ballerina-lang/ballerina#2938]
Eg: `License` should be only valid inside `ServiceInfo`
```
@swagger:ServiceInfo {
    license: @swagger:License {}
}
```
But currently following is also recognized as a valid input.
```
@swagger:License {}
function main (string[] args) {
}
```
Suggestion:
Make annotations without attachment points only valid inside the explicitly defined in-annotation variables.

**Comment by SupunS** [comment]
A possible solution is to let a user define the attachment point as `none`. Or to make the default case to attach none.

**Comment by hasithaa** [comment]
We no longer have this issue with new annotation design. Now annotations are records and only marked annotations can be used as an annotation.
