### ISSUE TITLE
[WebSocket] Detected Memory Leak while doing Load Test

### ISSUE THREAD

**Issue by irunika** [ballerina-lang/ballerina#3832]
We were able to detect a memory leak in WebSocket during load test in a pass-through scenario. It is mainly because not correctly releasing netty byte buffs in transport. SO these netty byte buffs have to be released carefully and should rethink how to release them after usage.

**Comment by riyafa** [comment]
A test was run to measure the memory using the old websocket implementation and the new. 
The JMC analysis of the memory usage is as follows:
**Previous implementation:**
![rfr-old](https://user-images.githubusercontent.com/8238078/36240235-51f1579c-1236-11e8-89c6-0e0cd7752edf.png)
The memory seems to grow in this case.

**After fixing memory leak:**
![rfr-new](https://user-images.githubusercontent.com/8238078/36240247-6b0d6824-1236-11e8-8ae8-d6577001da73.png)
The memory change is stable.
