### ISSUE TITLE
[HTTP] HTTP2 support

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-lang/ballerina#3954]
Both server and client connectors need to support this.

**Comment by isudana** [comment]
Design document https://docs.google.com/document/d/1mxoVFWR2_Ma67DpsekZU0T7rdkMdEJfnT_bnA75hU0g/edit#

**Comment by isudana** [comment]
As per the above design,
HTTP/2 support will be added to the HTTP Server connector and there will be a separate connector called HTTP2Client which supports HTTP/2
