### ISSUE TITLE
Constrained Ballerina Map type

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-lang/ballerina#4075]
The developer should be able to define a variable of type 'map' to hold on integers or strings etc. The key will always string type.

e.g. 

map<int> ints = {};

**Comment by djkevincr** [comment]
Design Documentation. https://docs.google.com/document/d/1NvCbWflnVICt__Ceg-hx9rrIHT7GdpAtZxPpW9Y1O1g/edit

**Comment by djkevincr** [comment]
https://github.com/ballerina-lang/ballerina/pull/4373 PR addresses this. Hence closing.
