### ISSUE TITLE
Struct/Connector equivalency

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-lang/ballerina#4084]
Please refer the following document 

https://docs.google.com/document/d/1AlGUoVIQ3SoSN6ZlA3zeabAtkBHDUW2F_Unpnh9q8Oo/edit#heading=h.224e6ing75zy

**Comment by hasithaa** [comment]
Struct equivalency is added by @sameera-jayasoma with https://github.com/ballerina-lang/ballerina/pull/4535

**Comment by hasithaa** [comment]
Connectors are dropped from the language. Struct/Object equivalency is added, Hence closing this issue.
