### ISSUE TITLE
Need an option to configure the file path of a config file when reading properties

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/ballerina#4091]
I want to read parameters from a config file without specifying the file path when running the app. Currently,  we have the following limitations to do so.
1. Have the file in the same directory where you run the app
2. Have the file name as "ballerina.conf"

Otherwise we have to run like below.
eg: `ballerina run -Bballerina.conf=./resources/gmail-con.conf  services`

I want to have the file in the name and location I want and run the application without passing the location. So shall we have another method where the user can specify the file location?

**Comment by pubudu91** [comment]
What you are saying seems contradictory. The config API has the following hierarchy when processing configurations.

1. Runtime parameters (provided by the user through the CLI using the `-B` flag)
2. Environment variables
3. Config file (by default, Ballerina looks at the source root path for a file named `ballerina.conf`. If it is present, the configurations in this file are considered. Alternatively, the users can provide the location of the config file as a runtime parameter, using the -Bballerina.conf flag.)
4. Default configs (these are hard coded values)

If your requirement is to let the user specify the location of the config file, the mentioned approach is the correct one: `-Bballerina.conf=./resources/gmail-con.conf`

**Comment by dilinisg** [comment]
Hi, 
Currently, we must specify the file path as a runtime configuration as you correctly mentioned which I need to avoid. 

What I expect is to specify the file path in the code itself.
For e.g. `config:getGlobalValue(filePath, "username.instances");`

Hope this clarifies the issue.

**Comment by pubudu91** [comment]
Closing this since we condone reading from multiple configuration files.
