### ISSUE TITLE
Endpoint can be passed to an any type variable

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-lang/ballerina#4167]
Below code works 
```ballerina
import ballerina.net.http;

public function main (string[] args) {
    endpoint<http:HttpClient> ep {

    }
    any ll = ep;
    println("Hello, World!");
}
```
and endpoint can be pass around using any type

**Comment by hasithaa** [comment]
@lankavitharana , After Discussing with Sanjiva, we decide to not support this. Endpoint doesn't belong to the type system. Hence we can't assign this to any

**Comment by hasithaa** [comment]
We have refactored endpoint design with release 0.965.0. This is allowed with the new change.
