### ISSUE TITLE
[WebSocket] Need association between ws:HandshakeConnection and ws:Connection

### ISSUE THREAD

**Issue by irunika** [ballerina-lang/ballerina#4299]
**Description:**
Basically ws:Handshake connection is the connection before the handshake and ws:Connection is the connection after the handshake. But there is some association between them and it is not reflected in the current implementation of WebSocket. 
eg: attributes map is a common place where you can put any object inside and take it out. This is needed in proxy scenarios.
 
**Steps to reproduce:**
N/A

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**

N/A

**Suggested Labels (optional):**

Task

**Suggested Assignees (optional):**

N/A

**Comment by riyafa** [comment]
Not applicable in the current design
