### ISSUE TITLE
Can not access xml child element when there is a namespace and 'return' word as the parent.

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-lang/ballerina#4360]
**Description:**

Consider a xml payload like this. 
`<ns:addOrderResponse
	xmlns:ns="http://ws.starbucks.com">
	<ns:return
		xmlns:ax2431="http://ws.starbucks.com/xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax2431:Order">
		<ax2431:additions>Milk</ax2431:additions>
		<ax2431:cost>10.8</ax2431:cost>
		<ax2431:drinkName>Caffe Misto</ax2431:drinkName>
		<ax2431:locked>false</ax2431:locked>
		<ax2431:orderId>03f1d38c-edfa-4056-9d7b-e07c6cc9b7e0</ax2431:orderId>
		<ax2431:timestamp>2018-01-04T01:42:44Z</ax2431:timestamp>
	</ns:return>
</ns:addOrderResponse>`

When we try to access the cost element like this, 

xmlns "http://ws.starbucks.com" as m0;
payload.selectChildren(m0:return).selectChildren(ax2438:cost).getTextValue();

It shows an error as follows (because 'return' is considered as a keyword).
mismatched input ':'. expecting {'.', ',', ')', '[', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '@'}

It works fine when we replace the m0 with the namespace like this.
payload.selectChildren("{http://ws.starbucks.com}return").selectChildren(ax2438:cost).getTextValue();

This works fine if there is any other value except 'return'.

**Affected Versions:**
0.95.6

**Comment by SupunS** [comment]
This is because 'return' is a keyword. You can escape keywords using identifier literals (pipe notation).
eg: `payload.selectChildren(m0:|return|)`

**Comment by ponsilva** [comment]
Hi, 
how can I escape "return" keyword in 0.983?

When I use
selectDescendants(m0:|return|);

I get the errors
extraneous input '('
mismatched input '|'. expecting ';'

Thank you.
