### ISSUE TITLE
Composers has issues when run from a path with special chars

### ISSUE THREAD

**Issue by Malizor** [ballerina-lang/ballerina#4504]
**Description:**
When running the composer in a folder named with a "special" char, some features like running a program, debugging or the console do not work.

This happened easily for me, as my OS is in French so the Ballerina archive was downloaded in the "Téléchargements" folder and I extracted it there.

**Steps to reproduce:**
* Extract the latest Ballerina release in a folder named "ééééé"
* Launch the composer from there
* Try to run the "echo" example and notice that nothing happen

In the browser debug console I see that there is a POST request toward `http://127.0.0.1:9092/composer/fs/write` which failed with a 500 error and the following response: `{"Error":"No such file: /home/foobar/����/ballerina-tools-0.96.0/samples/echoService/echoService.bal"}`

**Affected Versions:**
Tested with 0.96.0 and 0.95.8.
**OS, DB, other environment details and versions:**
Firefox 58 on Ubuntu 17.10, OpenJDK 8.

**Comment by hemikak** [comment]
Hi @Malizor ,

We are moving this issue to the composer repository as it is related to the composer.

Please track this issue here: https://github.com/ballerinalang/composer/issues/5020

Hence closing this issue.

Regards,
Hemika

**Comment by kaviththiranga** [comment]
Re-opening this issue as now composer is merged with ballerina repo.
