### ISSUE TITLE
Add hover support for Lock statement

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-lang/ballerina#4570]
**Description:**
Need to support https://github.com/ballerina-lang/ballerina/pull/4537

**Related Issues (optional):**
https://github.com/ballerina-lang/ballerina/pull/4537

**Comment by NipunaMarcus** [comment]
This has been fixed hence closing this issue.
Duplicate issue: https://github.com/ballerina-lang/ballerina/issues/4770
