### ISSUE TITLE
Tool palette missing in Composer

### ISSUE THREAD

**Issue by markokocic** [ballerina-lang/ballerina#4658]
**Description:**
Tool palette is missing in Composer

**Steps to reproduce:**
Start Composer start script. Open any file. Tool Palette is not available.

**Affected Versions:**
at least 0.95 and later

**OS, DB, other environment details and versions:**
Windows. Any browser (IE, Chrome, Firefox, ...)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Tool palette has been removed from Composer purposely to improve the user experience. Now adding constructs to the code is allowed from the add button. If you open an empty source code it will consist of a add button as following screenshot. You can click the button and select from the preferred item you wan to include.

![screen shot 2018-02-14 at 5 01 43 pm](https://user-images.githubusercontent.com/2918812/36202031-2d32a49e-11a8-11e8-82f3-72e32ed45fe7.png)

![screen shot 2018-02-14 at 5 01 50 pm](https://user-images.githubusercontent.com/2918812/36202038-32d2e59e-11a8-11e8-9fc6-637fd091b3b7.png)

If your ballerina file already has code, it should display add buttons in the places where could add new code. This completely removes drag and drop user actions to add new statements, where user has to know where he can drop (Previously we tried to highlight and indicate areas which can be dropped). Now button menu will only list down possible statements can be added in the certain area. 

![screen shot 2018-02-14 at 5 02 09 pm](https://user-images.githubusercontent.com/2918812/36202117-7f8308b0-11a8-11e8-9dbd-578133133068.png)

![screen shot 2018-02-14 at 5 02 16 pm](https://user-images.githubusercontent.com/2918812/36202123-84a14a3c-11a8-11e8-84d1-6d26764aaa3f.png)

**Comment by markokocic** [comment]
Thanks for the info.
In this case you should update the screenshot at https://ballerinalang.org/ since it shows something that doesn't exist anymore.

**Comment by keizer619** [comment]
Yes you are correct, we have updated the website
