### ISSUE TITLE
[HTTP] Remove setting of default headers in outbound request from transport to ballerina

### ISSUE THREAD

**Issue by riyafa** [ballerina-lang/ballerina#4706]
**Description:**
The transport sets certain default headers to the client connector when it sends a message to the backend. This is not configurable and these headers should not be set in a pass through scenario. Hence setting of default headers should be done by ballerina and not by the HTTP-transport for more flexibility.

**Comment by shafreenAnfar** [comment]
To be specific it is only the Accept-Encoding header. We have remove that behaviour from the transport with merged PR.
