### ISSUE TITLE
Add Lock Statement Support for Completions

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-lang/ballerina#4771]
Original issue - https://github.com/ballerina-lang/language-server/issues/112

**Description:**
Need to support https://github.com/ballerinalang/ballerina/pull/4508

**Related Issues:**
https://github.com/ballerinalang/ballerina/pull/4508

**Comment by nadeeshaan** [comment]
Duplicate of https://github.com/ballerina-lang/ballerina/issues/4571 and Fixed with https://github.com/ballerina-lang/ballerina/pull/4694
