### ISSUE TITLE
Implement Find References language feature

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-lang/ballerina#4775]
Original issue - https://github.com/ballerina-lang/language-server/issues/101

**Description:**
Add the language feature [Find References](https://microsoft.github.io/language-server-protocol/specification#textDocument_references) for ballerina language server.

**Comment by NipunaMarcus** [comment]
References feature has been added to the language server with this PR, https://github.com/ballerina-lang/ballerina/pull/4739 hence closing this issue.
