### ISSUE TITLE
Code reformat results in empty content

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-lang/ballerina#4867]
When trying to format a file with following content, source format results in empty content. (v 0.963.0)

import ballerina.net.http;
import ballerina.time;
import ballerina.io;
import ballerina.data.sql;

string tableName = "EVENTS";

@http:configuration {
    basePath:"/events"
}
service<http> eventsDataService {

    endpoint<sql:ClientConnector> testDB {
          create sql:ClientConnector(sql:DB.MYSQL, "localhost", 3306,
            "events_db", "root", "root", {maximumPoolSize:5});
            // table: CREATE TABLE events(ID INT AUTO_INCREMENT, NAME VARCHAR(255), START_TIME  VARCHAR(255), VENUE VARCHAR(255), ORGANIZER_NAME VARCHAR(255), PRIMARY KEY (ID));
    }

    @http:resourceConfig {
        methods:["POST"],
        path:"/"
    }
    resource addEvent (http:Connection conn,http:InRequest req) {
        http:OutResponse res = {};
        json jsonPayload = req.getJsonPayload();
        var event, e = <Event> jsonPayload;
        if (e != null) {
            _ = conn.respond(errorToJson(e, res));
            return;
        }

        sql:Parameter[] params = [];
        sql:Parameter para1 = {sqlType:sql:Type.VARCHAR, value:event.name};
        sql:Parameter para2 = {sqlType:sql:Type.VARCHAR, value:event.start_time};
        sql:Parameter para3 = {sqlType:sql:Type.VARCHAR, value:event.venue};
        sql:Parameter para4 = {sqlType:sql:Type.VARCHAR, value:event.organizer_name};

        table dt = testDB.select("SELECT * FROM "+tableName+" WHERE NAME = ?", [para1], null);
        var jsonRes, err = <json>dt;
        json jsonResponse;
        if (jsonRes != null && !jsonRes.toString().equalsIgnoreCase("[]")) {
            jsonResponse = {"error" : event.name + " event is already added."};
            res.statusCode = 400;
            res.setJsonPayload(jsonResponse);
                _ = conn.respond(res);
            return;
        }

        params = [para1, para2, para3, para4];
        int ret = testDB.update("INSERT INTO "+tableName+" (NAME,START_TIME,VENUE,ORGANIZER_NAME) VALUES (?,?,?,?)", params);
        
        if (ret == 1) {
            jsonResponse, _ = <json>event;
        } else {
            jsonResponse = {"error" : event.name + " event could not be added."};
            res.statusCode = 400;
        }

            res.setJsonPayload(jsonResponse);
                _ = conn.respond(res);
    }

    @http:resourceConfig {
        methods:["GET"],
        path:"/{name}"
    }
    resource getEvent (http:Connection conn,http:InRequest req, string name) {
        http:OutResponse res = {};
        map params = req.getQueryParams();

        sql:Parameter para1 = {sqlType:sql:Type.VARCHAR, value:name};
        table dt = testDB.select("SELECT * FROM "+tableName+" WHERE NAME = ?", [para1], null);
        var jsonRes, e = <json>dt;
        if (e != null) {
            _ = conn.respond(errorToJson(e, res));
            return;
        } else {
            res.setJsonPayload(jsonRes);
            _ = conn.respond(res);
        }
    }

    @http:resourceConfig {
        methods:["DELETE"],
        path:"/{name}"
    }
    resource deleEvent (http:Connection conn,http:InRequest req, string name) {
        http:OutResponse res = {};
        map params = req.getQueryParams();

        sql:Parameter para1 = {sqlType:sql:Type.VARCHAR, value:name};
        table dt = testDB.select("SELECT * FROM "+tableName+" WHERE NAME = ?", [para1], null);
        var jsonRes, e = <json>dt;
        if (e != null) {
            _ = conn.respond(errorToJson(e, res));
            return;
        } else {
            res.setJsonPayload(jsonRes);
            _ = conn.respond(res);
        }
    }
    
}

function errorToJson (error e, http:OutResponse res) (http:OutResponse) {
            var jsonError, _ = <json> e;
            res.setJsonPayload(jsonError);
            res.statusCode = 400;
            return res;
}

// Represents a single event
struct Event {
    // name of the event
    string name;
    // start time of the event
    string start_time;
    // venue
    string venue;
    // string organizer name
    string organizer_name;
}

**Comment by hevayo** [comment]
The syntax is no longer valid in 0.970.0
