### ISSUE TITLE
!= doesn't work for function pointers

### ISSUE THREAD

**Issue by afkham** [ballerina-lang/ballerina#4997]
**Description:**
If the != operator is used with function pointers, compilation will fail with the following error:
operator '!=' not defined for 'function (string) returns (string)' and 'null'

**Steps to reproduce:**
The following code will reproduce the issue

```ballerina
import ballerina.io;

struct SampleStruct {
    function (string s) returns (string) fnPointer;
}

public function main (string[] args) {
    SampleStruct sample = {};
    sample.fnPointer = foo;
    if(sample.fnPointer != null) {
        string myS = sample.fnPointer("Azeez");
        io:println(myS);
    }
}

function foo(string s) returns (string) {
    return s + "hello";
}
```

**Comment by djkevincr** [comment]
PR https://github.com/ballerina-lang/ballerina/pull/4998 merged. Hence closing.
