### ISSUE TITLE
Resource is not properly mapped according to the path

### ISSUE THREAD

**Issue by hemikak** [ballerina-lang/ballerina#5016]
**Description:**
Correct resource is not mapped when using "*" wildcard resulting in method not found.

**Steps to reproduce:**
Have the following resource:
1. GET resource with path "{product}/*".
2. PUT resource with path "{product}/{id}".
3. DELETE resource with path "{product}/{id}".

Invoke a GET request with https://localhost:9090/stationary/5.

Results in method not found.

**Affected Versions:**
Ballerina 0.963.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Mac

**Comment by chamil321** [comment]
Duplicate
https://github.com/ballerina-lang/ballerina/issues/4948

**Comment by chamil321** [comment]
https://github.com/ballerina-lang/ballerina/pull/5055 has addressed the issue. hence closing it
