### ISSUE TITLE
Add HTTP/2 related actions to composer

### ISSUE THREAD

**Issue by isudana** [ballerina-lang/ballerina#5189]
**Description:**
HTTP/2 support for HTTP connector will be added through 
https://github.com/ballerina-lang/ballerina/pull/5188

Need to add composer support for newly added actions.
Please refer to following document to find out new actions.

https://docs.google.com/document/d/1mxoVFWR2_Ma67DpsekZU0T7rdkMdEJfnT_bnA75hU0g/edit#

**Comment by keizer619** [comment]
As actions list is populated dynamically it should work out of box. Hence i am closing this issue.
