### ISSUE TITLE
Remove ConnectorStartupSynchronizer from the code

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-lang/ballerina#5210]
**Description:**
This was originally introduced to wait till all the services are completed. The rule was if one of the services fails to deploy we need to roll back all the services. In order to do so we had this delayed port binding implementation which don't need anymore.

https://github.com/ballerina-lang/ballerina/blob/master/stdlib/ballerina-http/src/main/java/org/ballerinalang/net/http/util/ConnectorStartupSynchronizer.java

**Comment by chamil321** [comment]
https://github.com/ballerina-lang/ballerina/pull/6052 has addressed the issue, Hence closing it.
