### ISSUE TITLE
Public types not supported

### ISSUE THREAD

**Issue by TharinduNM** [ballerina-lang/ballerina#5629]
**Description:**
When I declare something as `public type Person object`, it gives an error when accessing from outside the package.

**Steps to reproduce:**
`package wso2.samples.typeChangeSyntax;

import ballerina.io;
public type Person object {
        public {
            int age;
            string name;
            int cid;
        }
        private {
            string id;
        }

        new (int a,string n,string i) {
            age = a;
            name = n;
            id = i;
            cid = 1022;
        }
       
        function foo() returns (int, string) | error {
            if (age<10) {
                error e = {};
                e.message = "sfeege";
                return e;
            }
            else {
                return (cid, name);
            }
        }
    }`

When I try to access this type Person from outside the package it gives the following error.

`error: wso2.samples.typeChangeSyntax/connector.bal:5:8: invalid token 'type'
compilation contains errors`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Shan1024** [comment]
When did you last get the upstream changes?
