### ISSUE TITLE
Constrained maps do not allow insertion of polymorphic subtypes

### ISSUE THREAD

**Issue by afkham** [ballerina-lang/ballerina#5954]
**Description:**
TwoPhaseTransaction is subtype polymorphic to Transaction.

I have declared my map as follows
```ballerina
map<Transaction> m;
```

```ballerina
TwoPhaseCommitTransaction twopc = {};
Transaction t = twopc;
m["tid"] = t; // This fails at runtime
```

The runtime error is; 
caused by error, message: invalid map insertion: expected value of type 'ballerina.transactions.coordinator:Transaction', found 'ballerina.transactions.coordinator:TwoPhaseCommitTransaction'

**Comment by djkevincr** [comment]
PR https://github.com/ballerina-lang/ballerina/pull/5959 addresses this hence closing.
