### ISSUE TITLE
HTTP client actions sometimes return null errors

### ISSUE THREAD

**Issue by afkham** [ballerina-lang/ballerina#5970]
**Description:**
HTTP client actions sometimes return null errors. I have noticed this mainly with the **respond** action.

ep -> respond(res) is always returning null when there is no error. The signature of respond should be http:HttpConnectorError|null

**Comment by chamil321** [comment]
https://github.com/ballerina-lang/ballerina/pull/5989 address the issue, Hence closing the issue
