### ISSUE TITLE
String to Json casting doesn't work

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-lang/ballerina#5976]
**Description:**
The string to json cast doesn't seem to work. The type of the resulting variable is still a string

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main (string[] args) {
    string str = "{\"name\":\"William\"}";
    var jsonVal = <json>str;
    io:println(typeof jsonVal);
}
```
**Output :** string

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by isharak** [comment]
ParseJson util method is introdused to parse JSON string and to generate a JSON object.

**Comment by vlgunarathne** [comment]
This issue was fixed in the PR https://github.com/ballerina-lang/ballerina/pull/5991
