### ISSUE TITLE
Custom Content-Type doesn't work.

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-lang/ballerina#6065]
**Description:**
Custom content-type doesn't work with the refactoring.

**Steps to reproduce:**
```java
endpoint http:ServiceEndpoint helloEP {
    port:9092
};

@Description {value:"Sample hello world service."}
service<http:Service> hello bind helloEP {

    @Description {value:"The helloResource only accepts requests made using the specified HTTP methods"}
    @http:ResourceConfig {
        methods:["POST", "PUT", "GET"],
        path:"/"
    }
    helloResource (endpoint outboundEP, http:Request req) {
        http:Response res = {};
        string payload = "json:sample json, <a>xml</a>";
        res.setHeader("Content-Type", "x-custome_type");
        blob blobPayload = payload.toBlob("UTF-8");
        res.setBinaryPayload(blobPayload);
        _ = outboundEP -> respond(res);
    }
}
```

Sample request: curl -v http://localhost:9092/hello

**Comment by arukshani** [comment]
@VijithaEkanayake @shafreenAnfar 

Syntax of the content-type >>  "Content-Type := type "/" subtype *[";" parameter] . If it's a custom content-type then it should take the form "x-custom-type/x-custom-sub-type" 

Please refer the spec https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by VijithaEkanayake** [comment]
cool. Missed to provide the subtype in the configurations. Thanks.
