### ISSUE TITLE
Config API returns null when a key has quotations

### ISSUE THREAD

**Issue by isurulucky** [ballerina-lang/ballerina#6105]
**Description:**
The config:getAsString lookup fails when the particular key/part of it has quotations 

**Steps to reproduce:**
Copy the following to ballerina.conf file:
["test: abc:123"]
groups="xxx,yyy,abc"

Use config:getAsString("test: abc:123.groups") to retrieve the config value. It returns null.

**Affected Versions:**
0.970.0-alpha1

**Comment by pubudu91** [comment]
Closed via #6108
