### ISSUE TITLE
Need to pass an endpoint as a parameter when creating another endpoint

### ISSUE THREAD

**Issue by TharinduNM** [ballerina-lang/ballerina#6116]
**Description:**
To minimize the dependability and improve the maintainability of ballerina connectors which use other connectors, the ability to pass an endpoint as a parameter when creating another endpoint is needed. But when try to pass an endpoint into another endpoint it gives the error `error: fail to compile file: null`.

Below is an example main function that reproduce the above error.

**Steps to reproduce:**
```

import ballerina/io;
import oauth2;

public function main (string[] args) {

    endpoint oauth2:OAuth2Endpoint oauthEP {
        <required parameters...>
    };

    endpoint Scim2Endpoint scimEP {
        oauthep: oauthEP
    };
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjiva** [comment]
The example written cannot be support and will not be supported.

That is, we are not going to allow one endpoint to be inited using another endpoint. Can you explain what you're really trying to do?

You can however declare a variable of the type oauth2:OAuth2Endpoint, init() it and then make that an init field of Scim2Endpoint. The concept of an endpoint is bigger than just the data object and that's why we are not going to allow you to init one endpoint using another.

**Comment by TharinduNM** [comment]
Currently I'm doing what you are suggesting. Having an oauth2:OAuth2Endpoint variable inside my connector struct, Initialize it inside my Scim2Endpoint init() and use it inside my connector functions. I'll continue doing that. Thanks for the clarification. 

Here is the reason why I tried to use an endpoint to initialize another endpoint. 

If the OAuth2 connector is changed, then the Scim2 connector needs to be refactored to include those changes, build again and upload to the Ballerina central. 
If we can pass an oauth2:OAuth2Endpoint to initialize the Scim2Endpoint then the changes made to OAuth2 connector won't affect the Scim2 connector. Therefore it would help to maintain huge number of connectors.

**Comment by sanjiva** [comment]
Well if the OAuth2 connecter changes the user code would have to change too. 

The fact that you use an OAuth2 connector inside the SCIM one is an implementation detail. And you do need to therefore be aware of implementation changes .. and you can use versioned imports too if you don't want to keep changing. (Not recommending that, especially now, but that's the architecture.)

If you agree please close this issue.
