### ISSUE TITLE
Different text sizes in directory structure

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-lang/ballerina#6323]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 12, 2017 at 16:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3687_

----

Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. The directory structure contain different text sizes. Let's have standard text size and styling to have an uniform effect.

![com_0 94_textsize](https://user-images.githubusercontent.com/15624590/31508278-2a9432da-af9b-11e7-88a2-0832429f222f.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Wednesday Nov 15, 2017 at 18:16 GMT_

----

The idea behind this difference is that the topmost folder is the Program directory and the rest that appear are directories supporting the package hierarchy. Hence the difference in emphasis

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/manuranga"><img src="https://avatars0.githubusercontent.com/u/1686124?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [manuranga](https://github.com/manuranga)**
_Friday Nov 17, 2017 at 12:09 GMT_

----

@dakshika @srsharon  Please verify this is ok, and please close if it is.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/srsharon"><img src="https://avatars0.githubusercontent.com/u/10986966?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [srsharon](https://github.com/srsharon)**
_Monday Jan 08, 2018 at 08:24 GMT_

----

The sizes in the directory have been brought to one fixed size. 

This has been fixed in the 0.96 release please find attached screen dump 
![image](https://user-images.githubusercontent.com/10986966/34663097-f4afb570-f47a-11e7-9877-06bea9d26531.png)

**Comment by srsharon** [comment]
![image](https://user-images.githubusercontent.com/10986966/38250520-a5cc893a-376c-11e8-82c0-2ee490655153.png)
This is Fixed in the 0.96 release
